# Generated by Django 5.0.7 on 2024-08-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_buyer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Profile_pic',
            field=models.FileField(default='Anonymous.jpg', upload_to='buyer_user_image/'),
        ),
    ]
