# Generated by Django 5.0.7 on 2024-08-14 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_buyer_app', '0004_cart_total'),
        ('ecom_seller_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_amount', models.IntegerField(default=0)),
                ('address', models.TextField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=40)),
                ('zipcode', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('ordernote', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_buyer_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qunatity', models.IntegerField(default=1)),
                ('total', models.IntegerField(default=0)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_buyer_app.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_seller_app.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_buyer_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField(default=0)),
                ('payment_status', models.CharField(blank=True, choices=[('Success', 'Success'), ('Fail', 'Fail')], max_length=20, null=True)),
                ('transaction_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('methods', models.CharField(max_length=40)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_buyer_app.order')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_buyer_app.user')),
            ],
        ),
    ]
