# Generated by Django 5.0.7 on 2024-08-16 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_seller_app', '0004_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
